// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropidadesApiMinimal.Data;

#nullable disable

namespace PropidadesApiMinimal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropidadesApiMinimal.Models.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("propiedads");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "Test 1",
                            FechaCreacion = new DateTime(2023, 9, 1, 11, 10, 47, 418, DateTimeKind.Local).AddTicks(757),
                            Nombre = "Casa las Palmas",
                            Ubicacion = "Cartagena"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = true,
                            Descripcion = "Test 2",
                            FechaCreacion = new DateTime(2023, 9, 1, 11, 10, 47, 418, DateTimeKind.Local).AddTicks(777),
                            Nombre = "Casa laureles",
                            Ubicacion = "Medellin"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = true,
                            Descripcion = "Test 2",
                            FechaCreacion = new DateTime(2023, 9, 1, 11, 10, 47, 418, DateTimeKind.Local).AddTicks(779),
                            Nombre = "Casa los Colores",
                            Ubicacion = "Bogotá"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
